load("@extensions_sdk//:defs.bzl", "js_extension")

package(default_visibility = ["//visibility:public"])

js_extension(
    name = "sample_extension",
    srcs = ["src/index.ts"],
    package_name = "js.sample",
    display_name = "Sample Extension (JS)",
    version = "1.0.0",
)
