load("@extensions_sdk//:defs.bzl", "go_extension")

go_extension(
    name = "sample_extension",
    srcs = ["main.go"],
    visibility = ["//visibility:public"],
    deps = [],
    package_name = "go.sample",
    display_name = "Sample Extension (Go)",
    version = "1.0.0",
)
