package(default_visibility = ["//visibility:public"])

alias(
    name = "extensions_go_proto",
    actual = "@extensions_sdk//protos:extensions_go_proto",
)

alias(
    name = "songs_go_proto",
    actual = "@extensions_sdk//protos:songs_go_proto",
)

alias(
    name = "ui_go_proto",
    actual = "@extensions_sdk//protos:ui_go_proto",
)
