[package]
name = "youtube"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
rusty_ytdl = { git = "https://github.com/Ovenoboyo/rusty_ytdl", default-features = false, features = ["search"] }
serde = "1.0.228"
serde_json = "1.0.148"
url = "2.5.7"
reqwest = "=0.12.23"

[lib]
crate-type = ["cdylib"]
path = "src/main.rs"

[patch.crates-io]
reqwest = { git = "https://github.com/Ovenoboyo/reqwest_extism", branch = "0.12.x" }


[profile.release]
lto = true
opt-level = 's'
